/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moyeora.myapp;


import java.util.List;
import moyeora.myapp.annotation.LoginUserArgumentResolver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.PropertySource;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.method.support.HandlerMethodArgumentResolver;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@SpringBootApplication
@EnableTransactionManagement
@PropertySource({
    "file:${user.home}/config/oauth.properties",
    "file:${user.home}/config/email.properties",
    "file:${user.home}/config/ncp.properties",
    "file:${user.home}/config/ncp-secret.properties"
})
@Controller
public class App implements WebMvcConfigurer {

    @Autowired
    LoginUserArgumentResolver loginUserArgumentResolver;

    public static void main(String[] args) throws Exception {
        System.out.println("##moyora test main() exec##");
        SpringApplication.run(App.class, args);
    }
    @GetMapping("/home")
    public void home() {
    }

    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
        resolvers.add(loginUserArgumentResolver);
    }
}
